algoport: "8081"
log:
  path: /var/log/sophliteos
  level: INFO
db:
  path: /var/lib/sophliteos/db/algoliteos.db
  savedays: 15
mediahost: 127.0.0.1:26080
picture:
  dir: /data/pictures
  maxsize: 1000
  quality: 90
algorithmhost: 127.0.0.1:35001
uploadhost: 127.0.0.1:8081
localhost: 127.0.0.1
abilities:
  1: "车轮泥土检测"
  2: "机动车违停"
  3: "未戴口罩"
  4: "非机动车乱停"
  5: "火焰监测"
  6: "突发性事件"
  7: "占道经营"
  8: "电动车检测"
  9: "离岗检测"
  16: "车牌识别"