task:
  base: '{"cameraId":"{{taskId}}","url":"{{streamUrl}}","imageOut":"base64","inputType":"RTSP","notifyUrl":"{{uploadUrl}}","skipFrame":25,"roi":[],"areaBoxes":[],"abilities":[{{abilities}}]}'
  eventMap:
    OccupationRoad: #  通道阻塞
      
      template: '{"name":"OccupationRoad","value":{"interval":0.2,"minTarry":3,"objMinCount":1,"alarmInterval":10,"featureCache":false,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    Smoking: #  吸烟检测
      
      template: '{"name":"Smoking","value":{"interval":0.2,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    FireOrSmokeDetected: #  烟火检测
      
      template: '{"name":"FireOrSmokeDetected","value":{"interval":0.2,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","objMinCount":1,"mergeEnable":true,"roi":[]}}'
    HumanBreakIn: #  人员入侵
      
      template: '{"name":"HumanBreakIn","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    Sleeping: # 睡岗
      
      template: '{"name":"Sleeping","value":{"interval":0.2,"minTarry":3,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":"{{hotRegion}}"}}'
    PeopleWithoutMask: # 未戴口罩
      
      template: '{"name":"PeopleWithoutMask","value":{"interval":0.2,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    SingleVehicleSnap: # 车型识别
      
      template: '{"name":"SingleVehicleSnap","value":{"interval":0.2,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    VehicleBreakIn: # 车辆闯入
      
      template: '{"name":"VehicleBreakIn","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    VehicleLicenseRecon: # 车牌识别
      
      template: '{"name":"VehicleLicenseRecon","value":{"interval":0.2,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    CameraOcclusion: # 摄像头遮挡
      
      template: '{"name":"CameraOcclusion","value":{"interval":0.2,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    NoneMotorVehicleParking: # 非机动车乱停
      
      template: '{"name":"NoneMotorVehicleParking","value":{"interval":2,"minTarry":10,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    UnexpectedEvents: # 突发性事件
      
      template: '{"name":"UnexpectedEvents","value":{"interval":0.4,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"areaBoxes":"{{hotRegion}}","personCount":5,"roi":[]}}'
    RoadOccupatedInOperation: # 占道经营
      
      template: '{"name":"RoadOccupatedInOperation","value":{"interval":0.2,"minTarry":4,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","mergeEnable":false,"roi":[]}}'
    ElectricCarEntersElevator: # 电动车检测
      
      template: '{"name":"ElectricCarEntersElevator","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"objMinCount": 1,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    OccupationOfFireAccess: # 占用消防通道
      
      template: '{"name":"OccupationOfFireAccess","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    GarbageExposed: # 垃圾暴露
      
      template: '{"name":"GarbageExposed","value":{"interval":0.5,"minTarry":3,"alarmInterval":5,"minBox":{"width":50,"height":50},"threshold":0.4,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    GarbageOverflow: # 垃圾满溢
      
      template: '{"name":"GarbageOverflow","value":{"interval":0.5,"minTarry":3,"alarmInterval":5,"minBox":{"width":50,"height":50},"threshold":0.4,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    SmokeDetected: # 烟雾检测
      
      template: '{"name":"SmokeDetected","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    FireDetected: # 火焰监测
      
      template: '{"name":"FireDetected","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    LoessExposed: # 裸土识别
      
      template: '{"name":"LoessExposed","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    RoadPonding: # 积水识别
      
      template: '{"name":"RoadPonding","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    MotorVehicleParking: # 机动车违停
      
      template: '{"name":"MotorVehicleParking","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    OffStoreOperation: # 出店经营
      
      template: '{"name":"OffStoreOperation","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    IllegalOutdoorAdvertising: # 户外广告牌识别
      
      template: '{"name":"IllegalOutdoorAdvertising","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    BannerOrSlogansHungging: # 拉横幅识别
      
      template: '{"name":"BannerOrSlogansHungging","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    HangDownTheStreet: # 沿街晾晒
      
      template: '{"name":"HangDownTheStreet","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    ManholeCoverDamaged: # 井盖识别
      
      template: '{"name":"ManholeCoverDamaged","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    ConstructionTruck: # 渣土车抓拍
      
      template: '{"name":"ConstructionTruck","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false, "areaBoxes":"{{hotRegion}}","roi":[]}}'
    MotorVehicleBreakIn: # 机动车识别（不带车牌）
      
      template: '{"name":"MotorVehicleBreakIn","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    WithoutHelmetOnSite: # 安全帽识别（未带）
      
      template: '{"name":"WithoutHelmetOnSite","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    EngineeringVehicle: # 工程车辆检测
      
      template: '{"name":"EngineeringVehicle","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    RoadOccupatedInConstruction: # 施工占道
      
      template: '{"name":"RoadOccupatedInConstruction","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    RoadDamaged: # 道路破损
      
      template: '{"name":"RoadDamaged","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    HeapOfMaterial: # 乱堆物料
      
      template: '{"name":"HeapOfMaterial","value":{"interval":1,"alarmInterval":10,"minTarry":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    OccupationOfBarrierFreeAccess: # 占用无障碍通道
      
      template: '{"name":"OccupationOfBarrierFreeAccess","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    PlayPhone: # 使用手机检测
      
      template: '{"name":"PlayPhone","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    Fishing: # 非法垂钓
      
      template: '{"name":"Fishing","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    OffDutyAlarm: # 离岗检测
      
      template: '{"name":"OffDutyAlarm","value":{"interval":0.2,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    WithoutSafeHelmet: # 安全头盔识别（未带）
      
      template: '{"name":"WithoutSafeHelmet","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    NoneMotorVehicleBreakIn: # 非机动车识别
      
      template: '{"name":"NoneMotorVehicleBreakIn","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    GroundDust: # 扬尘监测
      
      template: '{"name":"GroundDust","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    Climbing: # 人员攀爬
      
      template: '{"name":"Climbing","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    PersonNumber: # 人流密度
      
      template: '{"name":"PersonNumber","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    FollowIntoHousePerson: # 人员尾随入户
      
      template: '{"name":"FollowIntoHousePerson","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    WithoutChefHat: # 厨师帽识别
      
      template: '{"name":"WithoutChefHat","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    WearDetection: # 白色厨师服识别
      
      template: '{"name":"WearDetection","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    PersonnelFalls: # 人员摔倒
      
      template: '{"name":"PersonnelFalls","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    HumanCrossTheBorder: # 越界识别
      
      template: '{"name":"HumanCrossTheBorder","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    PassengerFlow: # 客流统计
      
      template: '{"name":"PassengerFlow","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    Retrograde: # 车辆逆行识别
      
      template: '{"name":"Retrograde","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","areaParams":{{retrogradeRegion}},"roi":[]}}'
    SmokyEngineeringVehicle: # 工程车冒黑烟
      
      template: '{"name":"SmokyEngineeringVehicle","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    HumanHover: # 徘徊识别
      
      template: '{"name":"HumanHover","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    ResidueAccumulation:  # 积存垃圾渣土
      
      template: '{"name":"ResidueAccumulation","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    UnlicensedBusinessVendor: # 无照经营游商
      
      template: '{"name":"UnlicensedBusinessVendor","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    RoadSprinklerDetection: # 道路抛洒物检测
      
      template: '{"name":"RoadSprinklerDetection","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    StickerAds: # 非法小广告
      
      template: '{"name":"StickerAds","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    ChannelBlockage: # 通道阻塞
      
      template: '{"name":"ChannelBlockage","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    TransportVehicleUncovered: # 渣土车未密闭运输
      
      template: '{"name":"TransportVehicleUncovered","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    RealTimeVehicleCount: # 车辆计数
      
      template: '{"name":"RealTimeVehicleCount","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    WithoutHelmetWithMotorBike: # 摩托车不戴头盔
      
      template: '{"name":"WithoutHelmetWithMotorBike","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    RealTimePersonCount: # 人流量检测
      
      template: '{"name":"RealTimePersonCount","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    JumpWallDetected: # 违规翻越
      
      template: '{"name":"JumpWallDetected","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
    DrownDetection: # 游泳
    
      template: '{"name":"DrownDetection","value":{"interval":1,"alarmInterval":10,"minBox":{"width":50,"height":50},"threshold":0.4,"arealsReverse":false,"areaBoxes":"{{hotRegion}}","roi":[]}}'
