"project_id": "667578"
"api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6IjRhYzVjZmYxZjlmNzdiMjNhYTY0OTJhOWFkN2IyZGIwN2QyNzk3NjJjN2QxYzNiMjJkOGFmYmJhOWFiMDA1ZDM0ZTA0M2E3MTJkMjllOGQzIiwiaWF0IjoxNzIwNTc3NDIyLjM1MDMzMSwibmJmIjoxNzIwNTc3NDIyLjM1MDMzNCwiZXhwIjoxNzUyMTEzNDIyLjI3NjgwMSwic3ViIjoiMTYzMzI4MTIiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.gmB0NkWFnum3tk8APZdHcFrK_GONma3FTEUx9FOstoI5bthBYVmdKEasoyQqKY3CL6JE7nNcvylR3I60B8Ct_Drmf_8WuqwI4cLOfheo4bXu6sGIS6kYT9DwXIh8GnHtJyl_KB-mpr9obtqwittsnYsYKABiL0HrX_Obo6aTSpunUmC1YkWFa7dqbhLaWEeGLsq-wUlBOpMHKajlzuHju0ipzcpiYjaohvV0uI4r0WYASXlufPsCjs4r7MDPHjJwVdlj9C_ONmcUfpbLI11mgxFVj8yXEiIFMMIR2SLBbvaQHiz2Sl4uIAtfOcivZXPno2RIuuhB7q4_Jabjko6oq-QbUF-GDnFf99UfGaMyIBGGtu_cRD8bwwhc-SpX4tSpGcUdmTtKetl2PTF1Wnn7_2uiBq9EWma9f4YbYZa2hOp5w5aYt5WE638wP2hgtlUAH3AT7_igzB6QYEJlNba0JRGJnBumaFOEYk9M3go9spTGFcj1fVQF3OFeAdP6KeJiVtSlDPL0rfEYsUG0P7iwk_SSFmGm2mrC1qYh__1Yu30BJ6az7zz9NrTiNWlLI3-8KIPcjCSuHK9bIZISU3Ih5gwnkchyVZDBmBvroltpXGetYc6GAlBVGdPvefrD-g6ynSlA-ZG5BwnjVHEZsxSd247g1joPmCIvNoc1kRpuVIY"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
  {
    "source": "/src/locales/lang/en/**/*.json",
    "translation" : "/src/locales/lang/%two_letters_code%/%original_file_name%",
    "type": "json"
  }
]